# Generated by Django 5.2.4 on 2025-12-11 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0001_initial'),
        ('attendance', '0002_dailysummaryreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.CharField(max_length=50)),
                ('mouza', models.CharField(blank=True, max_length=100, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('advance_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('balance_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deal_date', models.DateField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('customer_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incentives', to='attendance.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
