# Generated by Django 5.2.4 on 2025-12-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0002_incentive'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentive',
            name='total_paid_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
