# Generated by Django 5.2.4 on 2025-11-15 15:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0002_alter_activitylog_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('working_days', models.PositiveIntegerField(default=26, help_text='Total working days in the month')),
                ('late_mark_after', models.TimeField(default=datetime.time(9, 30))),
                ('late_deduction_per_minute', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('early_leave_before', models.TimeField(default=datetime.time(17, 0))),
                ('early_leave_deduction_per_minute', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
