# Generated by Django 5.2.4 on 2025-11-16 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0003_salaryconfig_delete_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryconfig',
            name='allowed_leaves',
            field=models.PositiveIntegerField(default=4, help_text='Number of paid leaves allowed per month'),
        ),
        migrations.AddField(
            model_name='salaryconfig',
            name='early_leave_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Early minutes threshold to count half-day'),
        ),
        migrations.AddField(
            model_name='salaryconfig',
            name='half_day_after_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Late minutes after which half-day applies'),
        ),
        migrations.AddField(
            model_name='salaryconfig',
            name='target_penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Penalty if monthly target not met', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='early_leave_before',
            field=models.TimeField(default=datetime.time(17, 0), help_text='If checkout before this time considered early'),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='early_leave_deduction_per_minute',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Per-minute early deduction (optional)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='late_deduction_per_minute',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Per-minute late deduction (optional)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='late_mark_after',
            field=models.TimeField(default=datetime.time(9, 30), help_text='After this time check-in considered late'),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, help_text='Monthly gross salary', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='working_days',
            field=models.PositiveIntegerField(default=26, help_text='Working days used to compute per-day salary'),
        ),
    ]
