# Generated by Django 5.2.4 on 2025-11-18 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0004_salaryconfig_allowed_leaves_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryconfig',
            name='allowed_leaves',
        ),
        migrations.RemoveField(
            model_name='salaryconfig',
            name='early_leave_before',
        ),
        migrations.RemoveField(
            model_name='salaryconfig',
            name='early_leave_deduction_per_minute',
        ),
        migrations.RemoveField(
            model_name='salaryconfig',
            name='early_leave_minutes',
        ),
        migrations.RemoveField(
            model_name='salaryconfig',
            name='half_day_after_minutes',
        ),
        migrations.RemoveField(
            model_name='salaryconfig',
            name='late_deduction_per_minute',
        ),
        migrations.RemoveField(
            model_name='salaryconfig',
            name='late_mark_after',
        ),
        migrations.AddField(
            model_name='salaryconfig',
            name='early_leave_allowed_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='salaryconfig',
            name='late_allowed_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='salaryconfig',
            name='target_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='target_penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='working_days',
            field=models.PositiveIntegerField(default=26),
        ),
    ]
