# Generated by Django 5.2.4 on 2025-10-14 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HourlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('report_hour', models.IntegerField()),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('work_done', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('reason_not_done', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_reports', to=settings.AUTH_USER_MODEL)),
                ('work_types', models.ManyToManyField(blank=True, related_name='hourly_reports', to='attendance.worktype')),
            ],
        ),
        migrations.CreateModel(
            name='WorkTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='attendance.worktype')),
            ],
        ),
        migrations.CreateModel(
            name='WorkDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('plot_number', models.CharField(blank=True, max_length=50, null=True)),
                ('project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_response', models.CharField(choices=[('interested', 'Interested'), ('not_interested', 'Not Interested'), ('not_sure', 'Not Sure')], max_length=15)),
                ('reason_not_interested', models.TextField(blank=True, null=True)),
                ('site_visit_done', models.BooleanField(default=False)),
                ('meeting_done', models.BooleanField(default=False)),
                ('booking_done', models.BooleanField(default=False)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('hourly_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='attendance.hourlyreport')),
                ('work_type_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.worktypeoption')),
            ],
        ),
        migrations.AddField(
            model_name='hourlyreport',
            name='work_type_options',
            field=models.ManyToManyField(blank=True, related_name='hourly_reports', to='attendance.worktypeoption'),
        ),
    ]
