# Generated by Django 5.2.4 on 2026-01-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummaryreport',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
