# Generated by Django 5.2.4 on 2026-01-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_dailysummaryreport_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_half_day',
            field=models.BooleanField(default=False),
        ),
    ]
