# Generated by Django 5.2.4 on 2025-10-13 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_faceregistration_avg_embedding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceregistration',
            name='user',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='FaceRegistration',
        ),
    ]
